all:
	pdflatex report.tex
	bibtex report
	pdflatex report.tex
	pdflatex report.tex

present:
	pdflatex present.tex
	bibtex present
	pdflatex present.tex
	pdflatex present.tex

diff:
	pdflatex diff.tex
	bibtex diff
	pdflatex diff.tex
	pdflatex diff.tex

clear:
	rm *.blg *.log *.pdf *.bbl *.aux
